# Generated by Django 4.2.3 on 2023-07-06 23:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('ingredient_name', models.CharField(max_length=100)),
                ('cas_number', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='IndependentMaterialAttribute',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(default='', max_length=100)),
                ('value', models.CharField(default='', max_length=100)),
                ('attributes', models.CharField(default='', max_length=100)),
                ('ingredient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.ingredient')),
            ],
        ),
    ]
