# Generated by Django 4.2.3 on 2023-07-07 23:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngredientProperty',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('value', models.FloatField(null=True)),
                ('boolean', models.BooleanField(null=True)),
                ('comment', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Interaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(null=True)),
                ('boolean', models.BooleanField(null=True)),
                ('comment', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='InteractionType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('alias', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PropertyType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('alias', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='ingredient',
            old_name='ingredient_name',
            new_name='name',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='alias',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='IndependentMaterialAttribute',
        ),
        migrations.AddField(
            model_name='interaction',
            name='ingredient1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='dependent_material1', to='backend.ingredient'),
        ),
        migrations.AddField(
            model_name='interaction',
            name='ingredient2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='dependent_material2', to='backend.ingredient'),
        ),
        migrations.AddField(
            model_name='interaction',
            name='interaction_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='backend.interactiontype'),
        ),
        migrations.AddField(
            model_name='ingredientproperty',
            name='ingredient_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.ingredient'),
        ),
        migrations.AddField(
            model_name='ingredientproperty',
            name='property_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='backend.propertytype'),
        ),
    ]
