# Generated by Django 4.2.3 on 2023-07-07 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_ingredientproperty_interaction_interactiontype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='alias',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='cas_number',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='interactiontype',
            name='alias',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='propertytype',
            name='alias',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='ingredientproperty',
            unique_together={('ingredient_id', 'property_type')},
        ),
        migrations.AlterUniqueTogether(
            name='interaction',
            unique_together={('ingredient1', 'ingredient2', 'interaction_type')},
        ),
    ]
