# Generated by Django 4.2.3 on 2023-07-08 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_alter_ingredient_alias_alter_ingredient_cas_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Functionality',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('alias', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('alias', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='ingredientproperty',
            name='boolean',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ingredientproperty',
            name='comment',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='ingredientproperty',
            name='value',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='boolean',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='comment',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='value',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='RecipeMetadata',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('percentage', models.DecimalField(decimal_places=3, max_digits=6)),
                ('funtionality', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.RESTRICT, to='backend.functionality', to_field='alias')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='backend.ingredient', to_field='alias')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.recipe', to_field='alias')),
            ],
            options={
                'unique_together': {('recipe', 'ingredient')},
            },
        ),
    ]
