# Generated by Django 4.2.3 on 2023-07-08 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_functionality_recipe_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormulaType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('alias', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Formula',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('alias', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='backend.formulatype', to_field='alias')),
            ],
            options={
                'unique_together': {('alias', 'type')},
            },
        ),
        migrations.CreateModel(
            name='FormulaMetadata',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('percentage', models.DecimalField(decimal_places=3, max_digits=6)),
                ('formula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.formula', to_field='alias')),
                ('funtionality', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.RESTRICT, to='backend.functionality', to_field='alias')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='backend.ingredient', to_field='alias')),
            ],
            options={
                'unique_together': {('formula', 'ingredient')},
            },
        ),
    ]
