# Generated by Django 4.2.3 on 2023-07-09 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_formulatype_formula_formulametadata'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormulaProperty',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('value', models.FloatField(blank=True, null=True)),
                ('boolean', models.BooleanField(blank=True, null=True)),
                ('comment', models.CharField(blank=True, max_length=200, null=True)),
                ('formula_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.formula')),
                ('property_type', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='backend.propertytype')),
            ],
            options={
                'unique_together': {('formula_id', 'property_type')},
            },
        ),
    ]
