# Generated by Django 4.2.3 on 2023-07-09 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_equipment_experiment_process_qualitativetype_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='formulametadata',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='recipemetadata',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='formulametadata',
            name='ingredient_component',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.RESTRICT, to='backend.ingredient', to_field='alias'),
        ),
        migrations.AddField(
            model_name='formulametadata',
            name='recipe_component',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.RESTRICT, to='backend.recipe', to_field='alias'),
        ),
        migrations.AddField(
            model_name='recipemetadata',
            name='formula_component',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.RESTRICT, to='backend.formula', to_field='alias'),
        ),
        migrations.AddField(
            model_name='recipemetadata',
            name='ingredient_component',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.RESTRICT, to='backend.ingredient', to_field='alias'),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='recipe',
            field=models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to='backend.recipe', to_field='alias'),
        ),
        migrations.AlterField(
            model_name='experimentmethod',
            name='step',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='experimentvalidation',
            name='step',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='formulametadata',
            name='funtionality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='backend.functionality', to_field='alias'),
        ),
        migrations.AlterField(
            model_name='recipemetadata',
            name='funtionality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='backend.functionality', to_field='alias'),
        ),
        migrations.AlterUniqueTogether(
            name='formulametadata',
            unique_together={('formula', 'ingredient_component'), ('formula', 'recipe_component')},
        ),
        migrations.AlterUniqueTogether(
            name='recipemetadata',
            unique_together={('recipe', 'formula_component'), ('recipe', 'ingredient_component')},
        ),
        migrations.RemoveField(
            model_name='formulametadata',
            name='ingredient',
        ),
        migrations.RemoveField(
            model_name='recipemetadata',
            name='ingredient',
        ),
    ]
