# Generated by Django 4.2.2 on 2023-07-16 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_experiment_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='quantitativeresult',
            name='value',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
