# Generated by Django 4.2.2 on 2023-07-21 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_quantitativeresult_value'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipemetadata',
            old_name='funtionality',
            new_name='functionality',
        ),
    ]
