# Generated by Django 4.2.2 on 2023-07-21 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_rename_funtionality_recipemetadata_functionality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientproperty',
            name='ingredient_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.ingredient', to_field='alias'),
        ),
        migrations.AlterField(
            model_name='ingredientproperty',
            name='property_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='backend.propertytype', to_field='alias'),
        ),
    ]
