# Generated by Django 4.2.2 on 2023-07-21 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_alter_ingredientproperty_ingredient_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interaction',
            name='ingredient1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='dependent_material1', to='backend.ingredient', to_field='alias'),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='ingredient2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='dependent_material2', to='backend.ingredient', to_field='alias'),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='interaction_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='backend.interactiontype', to_field='alias'),
        ),
    ]
